version: "3"

name: vanilla
services:
  vanilla:
    container_name: vanilla
    build:
      context: vanilla
      dockerfile: Dockerfile.dev
    env_file: env/vanilla.env
    command: >
      sh -c "poetry install --no-interaction --no-ansi --no-root --no-cache &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/vanilla
      - .poetry/venv:/vanilla/.venv
      - .poetry/cache:/root/.cache/pypoetry
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_started
  postgres:
    container_name: postgres
    image: postgres:13.15-alpine
    env_file:
      - env/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
